export const bangkokAttractions = [
  {
    placeId: 'seed-bkk-grand-palace',
    name: 'Grand Palace',
    description: 'Historic royal complex with ornate halls and temple architecture.',
    category: 'landmark',
    avgCost: 1200,
    avgDurationMinutes: 180,
    latitude: 13.750043,
    longitude: 100.491321,
    rating: 4.6,
    reviewCount: 50213,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'both',
    intensityLevel: 2,
    vibeTags: ['culture_nerd', 'adventurer'],
    bookingUrl: 'https://www.royalgrandpalace.th/en/home',
  },
  {
    placeId: 'seed-bkk-wat-arun',
    name: 'Wat Arun',
    description: 'Iconic riverside temple known for porcelain-decorated spires.',
    category: 'temple',
    avgCost: 250,
    avgDurationMinutes: 90,
    latitude: 13.743744,
    longitude: 100.488944,
    rating: 4.7,
    reviewCount: 28740,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'outdoor',
    intensityLevel: 2,
    vibeTags: ['culture_nerd', 'slow_traveller'],
    bookingUrl: 'https://www.tourismthailand.org/Attraction/wat-arun',
  },
  {
    placeId: 'seed-bkk-chatuchak-market',
    name: 'Chatuchak Weekend Market',
    description: 'Massive weekend market with street food, crafts, and fashion.',
    category: 'market',
    avgCost: 900,
    avgDurationMinutes: 180,
    latitude: 13.799999,
    longitude: 100.550003,
    rating: 4.5,
    reviewCount: 65431,
    bestTimeSlot: 'afternoon',
    indoorOutdoor: 'both',
    intensityLevel: 3,
    vibeTags: ['budget_explorer', 'foodie'],
    bookingUrl: 'https://www.chatuchakmarket.org',
  },
  {
    placeId: 'seed-bkk-iconsiam',
    name: 'ICONSIAM',
    description: 'Premium riverside mall with indoor floating market experience.',
    category: 'entertainment',
    avgCost: 1800,
    avgDurationMinutes: 150,
    latitude: 13.726136,
    longitude: 100.510155,
    rating: 4.7,
    reviewCount: 41890,
    bestTimeSlot: 'afternoon',
    indoorOutdoor: 'indoor',
    intensityLevel: 2,
    vibeTags: ['foodie', 'slow_traveller'],
    bookingUrl: 'https://www.iconsiam.com',
  },
  {
    placeId: 'seed-bkk-jim-thompson-house',
    name: 'Jim Thompson House Museum',
    description: 'Traditional Thai teak house museum featuring silk heritage.',
    category: 'museum',
    avgCost: 520,
    avgDurationMinutes: 90,
    latitude: 13.749258,
    longitude: 100.528774,
    rating: 4.4,
    reviewCount: 13320,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'indoor',
    intensityLevel: 1,
    vibeTags: ['culture_nerd', 'slow_traveller'],
    bookingUrl: 'https://www.jimthompsonhouse.org',
  },
  {
    placeId: 'seed-bkk-national-museum',
    name: 'Bangkok National Museum',
    description: 'Large collection of Thai art, archaeology, and royal artifacts.',
    category: 'museum',
    avgCost: 700,
    avgDurationMinutes: 120,
    latitude: 13.75635,
    longitude: 100.4932,
    rating: 4.5,
    reviewCount: 8870,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'indoor',
    intensityLevel: 1,
    vibeTags: ['culture_nerd', 'budget_explorer'],
    bookingUrl: 'https://www.virtualmuseum.finearts.go.th/nationalmuseumbangkok',
  },
  {
    placeId: 'seed-bkk-lumpini-park',
    name: 'Lumpini Park',
    description: 'Central green lung of Bangkok with lakes and morning exercise trails.',
    category: 'park',
    avgCost: 0,
    avgDurationMinutes: 90,
    latitude: 13.7307,
    longitude: 100.5418,
    rating: 4.6,
    reviewCount: 22914,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'outdoor',
    intensityLevel: 1,
    vibeTags: ['slow_traveller', 'budget_explorer'],
    bookingUrl: null,
  },
  {
    placeId: 'seed-bkk-asiatique',
    name: 'Asiatique The Riverfront',
    description: 'Riverside night bazaar with rides, shows, and dining.',
    category: 'nightlife',
    avgCost: 1400,
    avgDurationMinutes: 150,
    latitude: 13.7057,
    longitude: 100.5028,
    rating: 4.5,
    reviewCount: 27344,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'both',
    intensityLevel: 2,
    vibeTags: ['night_owl', 'foodie'],
    bookingUrl: 'https://www.asiatiquethailand.com',
  },
  {
    placeId: 'seed-bkk-mahanakhon-skywalk',
    name: 'King Power Mahanakhon SkyWalk',
    description: 'Sky deck with citywide views and glass-floor observation platform.',
    category: 'viewpoint',
    avgCost: 2200,
    avgDurationMinutes: 90,
    latitude: 13.7235,
    longitude: 100.5281,
    rating: 4.6,
    reviewCount: 14410,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'both',
    intensityLevel: 3,
    vibeTags: ['adventurer', 'night_owl'],
    bookingUrl: 'https://kingpowermahanakhon.co.th',
  },
  {
    placeId: 'seed-bkk-yaowarat',
    name: 'Yaowarat Street Food',
    description: 'Legendary Chinatown food street packed with late-night stalls.',
    category: 'food',
    avgCost: 850,
    avgDurationMinutes: 120,
    latitude: 13.7415,
    longitude: 100.5091,
    rating: 4.5,
    reviewCount: 19872,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'outdoor',
    intensityLevel: 2,
    vibeTags: ['foodie', 'budget_explorer'],
    bookingUrl: null,
  },
];
