export const dubaiAttractions = [
  {
    placeId: 'seed-dxb-burj-khalifa',
    name: 'Burj Khalifa',
    description: 'World\'s tallest tower with observation decks on high floors.',
    category: 'viewpoint',
    avgCost: 5200,
    avgDurationMinutes: 120,
    latitude: 25.1972,
    longitude: 55.2744,
    rating: 4.7,
    reviewCount: 129806,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'both',
    intensityLevel: 2,
    vibeTags: ['adventurer', 'culture_nerd'],
    bookingUrl: 'https://www.burjkhalifa.ae',
  },
  {
    placeId: 'seed-dxb-dubai-mall-aquarium',
    name: 'Dubai Aquarium & Underwater Zoo',
    description: 'Indoor marine attraction featuring tunnel walkthroughs and exhibits.',
    category: 'entertainment',
    avgCost: 3800,
    avgDurationMinutes: 120,
    latitude: 25.1975,
    longitude: 55.2796,
    rating: 4.5,
    reviewCount: 54880,
    bestTimeSlot: 'afternoon',
    indoorOutdoor: 'indoor',
    intensityLevel: 1,
    vibeTags: ['family', 'adventurer'],
    bookingUrl: 'https://thedubaiaquarium.com',
  },
  {
    placeId: 'seed-dxb-museum-of-the-future',
    name: 'Museum of the Future',
    description: 'Design-led technology museum with immersive themed floors.',
    category: 'museum',
    avgCost: 3600,
    avgDurationMinutes: 120,
    latitude: 25.2203,
    longitude: 55.2823,
    rating: 4.6,
    reviewCount: 43672,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'indoor',
    intensityLevel: 1,
    vibeTags: ['culture_nerd', 'adventurer'],
    bookingUrl: 'https://museumofthefuture.ae',
  },
  {
    placeId: 'seed-dxb-dubai-fountain-boardwalk',
    name: 'Dubai Fountain Boardwalk',
    description: 'Close-up promenade experience for fountain show views.',
    category: 'landmark',
    avgCost: 1400,
    avgDurationMinutes: 75,
    latitude: 25.1945,
    longitude: 55.2797,
    rating: 4.5,
    reviewCount: 14732,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'outdoor',
    intensityLevel: 1,
    vibeTags: ['slow_traveller', 'night_owl'],
    bookingUrl: 'https://www.emaar.com',
  },
  {
    placeId: 'seed-dxb-desert-safari',
    name: 'Desert Safari Dubai',
    description: 'Dune bashing, camel rides, and camp dinner in the desert.',
    category: 'nature',
    avgCost: 6500,
    avgDurationMinutes: 300,
    latitude: 24.996,
    longitude: 55.4862,
    rating: 4.7,
    reviewCount: 40221,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'outdoor',
    intensityLevel: 4,
    vibeTags: ['adventurer', 'night_owl'],
    bookingUrl: 'https://www.visitdubai.com',
  },
  {
    placeId: 'seed-dxb-marina-dhow-cruise',
    name: 'Dubai Marina Dhow Cruise',
    description: 'Night cruise with skyline views and dinner entertainment.',
    category: 'nightlife',
    avgCost: 3200,
    avgDurationMinutes: 150,
    latitude: 25.0804,
    longitude: 55.1403,
    rating: 4.4,
    reviewCount: 11657,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'both',
    intensityLevel: 1,
    vibeTags: ['night_owl', 'slow_traveller'],
    bookingUrl: 'https://www.visitdubai.com',
  },
  {
    placeId: 'seed-dxb-gold-souk',
    name: 'Gold Souk Dubai',
    description: 'Traditional market district known for jewelry and local trade.',
    category: 'market',
    avgCost: 2500,
    avgDurationMinutes: 120,
    latitude: 25.2708,
    longitude: 55.2963,
    rating: 4.4,
    reviewCount: 27044,
    bestTimeSlot: 'afternoon',
    indoorOutdoor: 'both',
    intensityLevel: 2,
    vibeTags: ['budget_explorer', 'culture_nerd'],
    bookingUrl: null,
  },
  {
    placeId: 'seed-dxb-al-fahidi',
    name: 'Al Fahidi Historical District',
    description: 'Heritage lanes and museums preserving old Dubai architecture.',
    category: 'landmark',
    avgCost: 700,
    avgDurationMinutes: 120,
    latitude: 25.2638,
    longitude: 55.2973,
    rating: 4.5,
    reviewCount: 19062,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'both',
    intensityLevel: 1,
    vibeTags: ['culture_nerd', 'slow_traveller'],
    bookingUrl: null,
  },
  {
    placeId: 'seed-dxb-aquaventure',
    name: 'Atlantis Aquaventure Waterpark',
    description: 'Large waterpark with slides, rapids, and marine encounters.',
    category: 'entertainment',
    avgCost: 7800,
    avgDurationMinutes: 300,
    latitude: 25.1304,
    longitude: 55.1171,
    rating: 4.6,
    reviewCount: 45127,
    bestTimeSlot: 'afternoon',
    indoorOutdoor: 'outdoor',
    intensityLevel: 4,
    vibeTags: ['adventurer', 'family'],
    bookingUrl: 'https://www.atlantis.com/dubai/aquaventure',
  },
  {
    placeId: 'seed-dxb-jumeirah-public-beach',
    name: 'Jumeirah Public Beach',
    description: 'Public beach with city skyline backdrop and jogging tracks.',
    category: 'beach',
    avgCost: 300,
    avgDurationMinutes: 150,
    latitude: 25.2048,
    longitude: 55.2343,
    rating: 4.5,
    reviewCount: 22011,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'outdoor',
    intensityLevel: 1,
    vibeTags: ['slow_traveller', 'budget_explorer'],
    bookingUrl: null,
  },
];
