export const goaAttractions = [
  {
    placeId: 'seed-goa-baga-beach',
    name: 'Baga Beach',
    description: 'Popular north Goa beach for water sports and sunset crowds.',
    category: 'beach',
    avgCost: 600,
    avgDurationMinutes: 180,
    latitude: 15.5553,
    longitude: 73.7517,
    rating: 4.4,
    reviewCount: 49100,
    bestTimeSlot: 'afternoon',
    indoorOutdoor: 'outdoor',
    intensityLevel: 2,
    vibeTags: ['adventurer', 'night_owl'],
    bookingUrl: null,
  },
  {
    placeId: 'seed-goa-calangute-beach',
    name: 'Calangute Beach',
    description: 'Goa\'s busiest beach strip with shacks and parasailing options.',
    category: 'beach',
    avgCost: 500,
    avgDurationMinutes: 180,
    latitude: 15.5439,
    longitude: 73.7553,
    rating: 4.3,
    reviewCount: 62044,
    bestTimeSlot: 'afternoon',
    indoorOutdoor: 'outdoor',
    intensityLevel: 2,
    vibeTags: ['budget_explorer', 'adventurer'],
    bookingUrl: null,
  },
  {
    placeId: 'seed-goa-chapora-fort',
    name: 'Chapora Fort',
    description: 'Hilltop fort ruins with sweeping Arabian Sea views.',
    category: 'viewpoint',
    avgCost: 120,
    avgDurationMinutes: 90,
    latitude: 15.6019,
    longitude: 73.7346,
    rating: 4.5,
    reviewCount: 33781,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'outdoor',
    intensityLevel: 3,
    vibeTags: ['adventurer', 'slow_traveller'],
    bookingUrl: null,
  },
  {
    placeId: 'seed-goa-basilica-bom-jesus',
    name: 'Basilica of Bom Jesus',
    description: 'UNESCO-listed baroque church and spiritual heritage landmark.',
    category: 'landmark',
    avgCost: 100,
    avgDurationMinutes: 75,
    latitude: 15.5008,
    longitude: 73.9113,
    rating: 4.6,
    reviewCount: 18954,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'both',
    intensityLevel: 1,
    vibeTags: ['culture_nerd', 'slow_traveller'],
    bookingUrl: null,
  },
  {
    placeId: 'seed-goa-fontainhas',
    name: 'Fontainhas',
    description: 'Colorful Latin quarter known for heritage homes and cafes.',
    category: 'landmark',
    avgCost: 350,
    avgDurationMinutes: 120,
    latitude: 15.4989,
    longitude: 73.8278,
    rating: 4.4,
    reviewCount: 10112,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'outdoor',
    intensityLevel: 1,
    vibeTags: ['culture_nerd', 'foodie'],
    bookingUrl: null,
  },
  {
    placeId: 'seed-goa-dudhsagar-falls',
    name: 'Dudhsagar Falls',
    description: 'Multi-tiered waterfall reached by jeep safari and short trek.',
    category: 'nature',
    avgCost: 1800,
    avgDurationMinutes: 240,
    latitude: 15.3144,
    longitude: 74.3145,
    rating: 4.5,
    reviewCount: 24390,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'outdoor',
    intensityLevel: 4,
    vibeTags: ['adventurer', 'budget_explorer'],
    bookingUrl: 'https://goatourism.gov.in',
  },
  {
    placeId: 'seed-goa-anjuna-flea-market',
    name: 'Anjuna Flea Market',
    description: 'Weekly beachside market for handicrafts, clothes, and snacks.',
    category: 'market',
    avgCost: 900,
    avgDurationMinutes: 150,
    latitude: 15.5745,
    longitude: 73.7409,
    rating: 4.3,
    reviewCount: 14772,
    bestTimeSlot: 'afternoon',
    indoorOutdoor: 'outdoor',
    intensityLevel: 2,
    vibeTags: ['budget_explorer', 'foodie'],
    bookingUrl: null,
  },
  {
    placeId: 'seed-goa-mandovi-cruise',
    name: 'Mandovi River Cruise',
    description: 'Evening cruise with live music and riverfront views.',
    category: 'entertainment',
    avgCost: 1300,
    avgDurationMinutes: 120,
    latitude: 15.5022,
    longitude: 73.8112,
    rating: 4.2,
    reviewCount: 12385,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'both',
    intensityLevel: 1,
    vibeTags: ['night_owl', 'slow_traveller'],
    bookingUrl: 'https://goatourism.gov.in',
  },
  {
    placeId: 'seed-goa-reis-magos-fort',
    name: 'Reis Magos Fort',
    description: 'Restored Portuguese fort museum overlooking the Mandovi river.',
    category: 'museum',
    avgCost: 250,
    avgDurationMinutes: 90,
    latitude: 15.5009,
    longitude: 73.8051,
    rating: 4.5,
    reviewCount: 9231,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'both',
    intensityLevel: 1,
    vibeTags: ['culture_nerd', 'slow_traveller'],
    bookingUrl: null,
  },
  {
    placeId: 'seed-goa-palolem-beach',
    name: 'Palolem Beach',
    description: 'Scenic crescent beach popular for kayaking and quieter sunsets.',
    category: 'beach',
    avgCost: 800,
    avgDurationMinutes: 180,
    latitude: 15.0101,
    longitude: 74.0232,
    rating: 4.6,
    reviewCount: 21267,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'outdoor',
    intensityLevel: 2,
    vibeTags: ['slow_traveller', 'foodie'],
    bookingUrl: null,
  },
];
