export const singaporeAttractions = [
  {
    placeId: 'seed-sg-gardens-by-the-bay',
    name: 'Gardens by the Bay',
    description: 'Futuristic waterfront gardens with conservatories and Supertrees.',
    category: 'park',
    avgCost: 3500,
    avgDurationMinutes: 180,
    latitude: 1.2816,
    longitude: 103.8636,
    rating: 4.7,
    reviewCount: 110522,
    bestTimeSlot: 'afternoon',
    indoorOutdoor: 'both',
    intensityLevel: 1,
    vibeTags: ['slow_traveller', 'culture_nerd'],
    bookingUrl: 'https://www.gardensbythebay.com.sg',
  },
  {
    placeId: 'seed-sg-zoo',
    name: 'Singapore Zoo',
    description: 'Open-concept wildlife park with immersive habitat zones.',
    category: 'nature',
    avgCost: 4500,
    avgDurationMinutes: 240,
    latitude: 1.4043,
    longitude: 103.793,
    rating: 4.6,
    reviewCount: 59731,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'outdoor',
    intensityLevel: 2,
    vibeTags: ['slow_traveller', 'adventurer'],
    bookingUrl: 'https://www.mandai.com/en/singapore-zoo.html',
  },
  {
    placeId: 'seed-sg-marina-bay-skypak',
    name: 'Marina Bay Sands SkyPark',
    description: 'Observation deck above Marina Bay skyline.',
    category: 'viewpoint',
    avgCost: 2600,
    avgDurationMinutes: 90,
    latitude: 1.2834,
    longitude: 103.8607,
    rating: 4.6,
    reviewCount: 34054,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'both',
    intensityLevel: 1,
    vibeTags: ['adventurer', 'night_owl'],
    bookingUrl: 'https://www.marinabaysands.com',
  },
  {
    placeId: 'seed-sg-national-museum',
    name: 'National Museum of Singapore',
    description: 'Flagship museum with multimedia exhibits on Singapore history.',
    category: 'museum',
    avgCost: 1200,
    avgDurationMinutes: 120,
    latitude: 1.2966,
    longitude: 103.8485,
    rating: 4.5,
    reviewCount: 15618,
    bestTimeSlot: 'morning',
    indoorOutdoor: 'indoor',
    intensityLevel: 1,
    vibeTags: ['culture_nerd', 'slow_traveller'],
    bookingUrl: 'https://www.nhb.gov.sg/nationalmuseum',
  },
  {
    placeId: 'seed-sg-maxwell-food-centre',
    name: 'Maxwell Food Centre',
    description: 'Hawker centre famous for local dishes and value meals.',
    category: 'food',
    avgCost: 900,
    avgDurationMinutes: 90,
    latitude: 1.2803,
    longitude: 103.8448,
    rating: 4.5,
    reviewCount: 21342,
    bestTimeSlot: 'afternoon',
    indoorOutdoor: 'indoor',
    intensityLevel: 1,
    vibeTags: ['foodie', 'budget_explorer'],
    bookingUrl: null,
  },
  {
    placeId: 'seed-sg-sentosa-cable-car',
    name: 'Sentosa Cable Car',
    description: 'Scenic cable car ride connecting Mount Faber and Sentosa.',
    category: 'entertainment',
    avgCost: 2400,
    avgDurationMinutes: 90,
    latitude: 1.2559,
    longitude: 103.8198,
    rating: 4.5,
    reviewCount: 17820,
    bestTimeSlot: 'afternoon',
    indoorOutdoor: 'both',
    intensityLevel: 2,
    vibeTags: ['adventurer', 'family'],
    bookingUrl: 'https://www.mountfaberleisure.com',
  },
  {
    placeId: 'seed-sg-chinatown-street-market',
    name: 'Chinatown Street Market',
    description: 'Bustling shophouse-lined market for snacks and souvenirs.',
    category: 'market',
    avgCost: 1500,
    avgDurationMinutes: 120,
    latitude: 1.2822,
    longitude: 103.8437,
    rating: 4.4,
    reviewCount: 17044,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'outdoor',
    intensityLevel: 2,
    vibeTags: ['foodie', 'budget_explorer'],
    bookingUrl: null,
  },
  {
    placeId: 'seed-sg-singapore-flyer',
    name: 'Singapore Flyer',
    description: 'Giant observation wheel overlooking Marina Bay district.',
    category: 'viewpoint',
    avgCost: 2500,
    avgDurationMinutes: 75,
    latitude: 1.2893,
    longitude: 103.8632,
    rating: 4.5,
    reviewCount: 28641,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'indoor',
    intensityLevel: 1,
    vibeTags: ['slow_traveller', 'culture_nerd'],
    bookingUrl: 'https://www.singaporeflyer.com',
  },
  {
    placeId: 'seed-sg-artscience-museum',
    name: 'ArtScience Museum',
    description: 'Lotus-shaped museum with digital and immersive installations.',
    category: 'museum',
    avgCost: 1900,
    avgDurationMinutes: 120,
    latitude: 1.2863,
    longitude: 103.8593,
    rating: 4.4,
    reviewCount: 22468,
    bestTimeSlot: 'afternoon',
    indoorOutdoor: 'indoor',
    intensityLevel: 1,
    vibeTags: ['culture_nerd', 'adventurer'],
    bookingUrl: 'https://www.marinabaysands.com/museum.html',
  },
  {
    placeId: 'seed-sg-night-safari',
    name: 'Night Safari',
    description: 'Nocturnal wildlife park with tram rides and walking trails.',
    category: 'nightlife',
    avgCost: 4200,
    avgDurationMinutes: 180,
    latitude: 1.4039,
    longitude: 103.7916,
    rating: 4.6,
    reviewCount: 32412,
    bestTimeSlot: 'evening',
    indoorOutdoor: 'outdoor',
    intensityLevel: 2,
    vibeTags: ['night_owl', 'adventurer'],
    bookingUrl: 'https://www.mandai.com/en/night-safari.html',
  },
];
